

export const NoPage = () => {
    return (
        <div style={{textAlign: 'center', fontFamily:"Hearts"}}>
            <p style={{zIndex: -1, position: 'absolute'}}> 
                SHES MY VALENTINE SHES MY VALENTINE SHES MY VALENTINE SHES MY VALENTINE
                SHES MY VALENTINE SHES MY VALENTINE SHES MY VALENTINE SHES MY VALENTINE
                SHES MY VALENTINE SHES MY VALENTINE SHES MY VALENTINE SHES MY VALENTINE
                SHES MY VALENTINE SHES MY VALENTINE SHES MY VALENTINE SHES MY VALENTINE
                SHES MY VALENTINE SHES MY VALENTINE SHES MY VALENTINE SHES MY VALENTINE
                SHES MY VALENTINE SHES MY VALENTINE SHES MY VALENTINE SHES MY VALENTINE
                SHES MY VALENTINE SHES MY VALENTINE SHES MY VALENTINE SHES MY VALENTINE
                SHES MY VALENTINE SHES MY VALENTINE SHES MY VALENTINE SHES MY VALENTINE
                SHES MY VALENTINE SHES MY VALENTINE SHES MY VALENTINE SHES MY VALENTINE
                SHES MY VALENTINE SHES MY VALENTINE SHES MY VALENTINE SHES MY VALENTINE
                SHES MY VALENTINE SHES MY VALENTINE SHES MY VALENTINE SHES MY VALENTINE
                SHES MY VALENTINE SHES MY VALENTINE SHES MY VALENTINE SHES MY VALENTINE
                SHES MY VALENTINE SHES MY VALENTINE SHES MY VALENTINE SHES MY VALENTINE
                SHES MY VALENTINE SHES MY VALENTINE SHES MY VALENTINE SHES MY VALENTINE
                SHES MY VALENTINE SHES MY VALENTINE SHES MY VALENTINE SHES MY VALENTINE
                SHES MY VALENTINE SHES MY VALENTINE SHES MY VALENTINE SHES MY VALENTINE
                SHES MY VALENTINE SHES MY VALENTINE SHES MY VALENTINE SHES MY VALENTINE
                SHES MY VALENTINE SHES MY VALENTINE SHES MY VALENTINE SHES MY VALENTINE
                SHES MY VALENTINE SHES MY VALENTINE SHES MY VALENTINE SHES MY VALENTINE
                SHES MY VALENTINE SHES MY VALENTINE SHES MY VALENTINE SHES MY VALENTINE
                SHES MY VALENTINE SHES MY VALENTINE SHES MY VALENTINE SHES MY VALENTINE
                SHES MY VALENTINE SHES MY VALENTINE SHES MY VALENTINE SHES MY VALENTINE
                SHES MY VALENTINE SHES MY VALENTINE SHES MY VALENTINE SHES MY VALENTINE
                SHES MY VALENTINE SHES MY VALENTINE SHES MY VALENTINE SHES MY VALENTINE
                SHES MY VALENTINE SHES MY VALENTINE SHES MY VALENTINE SHES MY VALENTINE
                SHES MY VALENTINE SHES MY VALENTINE SHES MY VALENTINE SHES MY VALENTINE
                SHES MY VALENTINE SHES MY VALENTINE SHES MY VALENTINE SHES MY VALENTINE
                SHES MY VALENTINE SHES MY VALENTINE SHES MY VALENTINE SHES MY VALENTINE
                SHES MY VALENTINE SHES MY VALENTINE SHES MY VALENTINE SHES MY VALENTINE
                SHES MY VALENTINE SHES MY VALENTINE SHES MY VALENTINE SHES MY VALENTINE
                SHES MY VALENTINE SHES MY VALENTINE SHES MY VALENTINE SHES MY VALENTINE
                SHES MY VALENTINE SHES MY VALENTINE SHES MY VALENTINE SHES MY VALENTINE
                SHES MY VALENTINE SHES MY VALENTINE SHES MY VALENTINE SHES MY VALENTINE
                SHES MY VALENTINE SHES MY VALENTINE SHES MY VALENTINE SHES MY VALENTINE
                SHES MY VALENTINE SHES MY VALENTINE SHES MY VALENTINE SHES MY VALENTINE
            </p>
        </div>
    );
}