import cat from '../images/happy-cat.gif'
import dog from '../images/happy-dog.gif'
import geese from '../images/lovey-geese.gif'

export const YesPage = () => {
    return (
        <div style={{textAlign: 'center', fontFamily:"Hearts"}}>
            <p style={{zIndex: -1, position: 'absolute'}}> 
                YOU'RE MY VALENTINE YOU'RE MY VALENTINE YOU'RE MY VALENTINE YOU'RE MY VALENTINE
                YOU'RE MY VALENTINE YOU'RE MY VALENTINE YOU'RE MY VALENTINE YOU'RE MY VALENTINE
                YOU'RE MY VALENTINE YOU'RE MY VALENTINE YOU'RE MY VALENTINE YOU'RE MY VALENTINE
                YOU'RE MY VALENTINE YOU'RE MY VALENTINE YOU'RE MY VALENTINE YOU'RE MY VALENTINE
                YOU'RE MY VALENTINE YOU'RE MY VALENTINE YOU'RE MY VALENTINE YOU'RE MY VALENTINE
                YOU'RE MY VALENTINE YOU'RE MY VALENTINE YOU'RE MY VALENTINE YOU'RE MY VALENTINE
                YOU'RE MY VALENTINE YOU'RE MY VALENTINE YOU'RE MY VALENTINE YOU'RE MY VALENTINE
                YOU'RE MY VALENTINE YOU'RE MY VALENTINE YOU'RE MY VALENTINE YOU'RE MY VALENTINE
                YOU'RE MY VALENTINE YOU'RE MY VALENTINE YOU'RE MY VALENTINE YOU'RE MY VALENTINE
                YOU'RE MY VALENTINE YOU'RE MY VALENTINE YOU'RE MY VALENTINE YOU'RE MY VALENTINE
                YOU'RE MY VALENTINE YOU'RE MY VALENTINE YOU'RE MY VALENTINE YOU'RE MY VALENTINE
                YOU'RE MY VALENTINE YOU'RE MY VALENTINE YOU'RE MY VALENTINE YOU'RE MY VALENTINE
                YOU'RE MY VALENTINE YOU'RE MY VALENTINE YOU'RE MY VALENTINE YOU'RE MY VALENTINE
                YOU'RE MY VALENTINE YOU'RE MY VALENTINE YOU'RE MY VALENTINE YOU'RE MY VALENTINE
                YOU'RE MY VALENTINE YOU'RE MY VALENTINE YOU'RE MY VALENTINE YOU'RE MY VALENTINE
                YOU'RE MY VALENTINE YOU'RE MY VALENTINE YOU'RE MY VALENTINE YOU'RE MY VALENTINE
                YOU'RE MY VALENTINE YOU'RE MY VALENTINE YOU'RE MY VALENTINE YOU'RE MY VALENTINE
                YOU'RE MY VALENTINE YOU'RE MY VALENTINE YOU'RE MY VALENTINE YOU'RE MY VALENTINE
                YOU'RE MY VALENTINE YOU'RE MY VALENTINE YOU'RE MY VALENTINE YOU'RE MY VALENTINE
                YOU'RE MY VALENTINE YOU'RE MY VALENTINE YOU'RE MY VALENTINE YOU'RE MY VALENTINE
                YOU'RE MY VALENTINE YOU'RE MY VALENTINE YOU'RE MY VALENTINE YOU'RE MY VALENTINE
                YOU'RE MY VALENTINE YOU'RE MY VALENTINE YOU'RE MY VALENTINE YOU'RE MY VALENTINE
                YOU'RE MY VALENTINE YOU'RE MY VALENTINE YOU'RE MY VALENTINE YOU'RE MY VALENTINE
                YOU'RE MY VALENTINE YOU'RE MY VALENTINE YOU'RE MY VALENTINE YOU'RE MY VALENTINE
                YOU'RE MY VALENTINE YOU'RE MY VALENTINE YOU'RE MY VALENTINE YOU'RE MY VALENTINE
                YOU'RE MY VALENTINE YOU'RE MY VALENTINE YOU'RE MY VALENTINE YOU'RE MY VALENTINE
                YOU'RE MY VALENTINE YOU'RE MY VALENTINE YOU'RE MY VALENTINE YOU'RE MY VALENTINE
                YOU'RE MY VALENTINE YOU'RE MY VALENTINE YOU'RE MY VALENTINE YOU'RE MY VALENTINE
                YOU'RE MY VALENTINE YOU'RE MY VALENTINE YOU'RE MY VALENTINE YOU'RE MY VALENTINE
                YOU'RE MY VALENTINE YOU'RE MY VALENTINE YOU'RE MY VALENTINE YOU'RE MY VALENTINE
                YOU'RE MY VALENTINE YOU'RE MY VALENTINE YOU'RE MY VALENTINE YOU'RE MY VALENTINE
                YOU'RE MY VALENTINE YOU'RE MY VALENTINE YOU'RE MY VALENTINE YOU'RE MY VALENTINE
                YOU'RE MY VALENTINE YOU'RE MY VALENTINE YOU'RE MY VALENTINE YOU'RE MY VALENTINE
                YOU'RE MY VALENTINE YOU'RE MY VALENTINE YOU'RE MY VALENTINE YOU'RE MY VALENTINE
                YOU'RE MY VALENTINE YOU'RE MY VALENTINE YOU'RE MY VALENTINE YOU'RE MY VALENTINE
            </p>

            <img style={{width: '25%'}} src={cat} />
            <img style={{width: '25%'}} src={dog} />

            <br/>

            <img style={{width: '20%'}} src={geese} />
        </div>
    );
}